// examples/todo-vuejs/src/components/units/TodoList.vue
<template>
  <ol>
    <TodoItem
      v-for="item in todolist"
      :key="item.id"
      :id="item.id"
      :text="item.text"
      :done="item.done"
    />
  </ol>
</template>

<script>
import TodoItem from './TodoItem'

import { connect } from '../../libs/vuejs/connect'

import { filteredTodolist } from '../../todo-core/projections/todo'

const TodoList = {
  name: 'TodoList',
  components: {
    TodoItem,
  },
  data: () => ({
    todolist: [],
  }),
}

export default connect({
  mapProtectedProjection: {
    todolist: filteredTodolist,
  },
})(TodoList)
</script>

// examples/todo/src/components/units/TodoList.svelte
<script>
  import { withProjection } from '@coriolis/coriolis-svelte'

  import TodoItem from './TodoItem.svelte'

  import { filteredTodolist } from '../../todo-core/projections/todo'

  let todolist$ = withProjection(filteredTodolist)
</script>

<ol class={$$props.class}>
{#each $todolist$ as item (item.id)}
  <TodoItem
    id={item.id}
    text={item.text}
    isDone={item.done}
  />
{/each}
</ol>
