// examples/todo-vuejs/src/components/units/ViewLink.vue
<template>
  <a :href="view" @click.prevent="trigger"><slot /></a>
</template>

<script>
import { connect } from '../../libs/vuejs/connect'

import { changeView } from '../../todo-core/commands/changeView'

const ViewLink = {
  name: 'ViewLink',
  props: {
    view: String,
  },
  methods: {
    trigger() {
      this.$emit('switch', this.view)
    },
  },
}

export default connect({
  eventDispatch: {
    switch: changeView,
  },
})(ViewLink)

</script>

// examples/todo/src/components/units/ViewLink.svelte
<script>
  import { createDispatch } from '@coriolis/coriolis-svelte'

  import { changeView } from '../../todo-core/commands/changeView'

  const dispatchChange = createDispatch(changeView)

  export let view

  const trigger = () => dispatchChange(view)
</script>

<a href={view} on:click|preventDefault={trigger}><slot /></a>
