// examples/todos/src/components/units/ViewLink.vue
<template>
  <a :href="view" @click.prevent="trigger"><slot /></a>
</template>

<script>
import { changed } from '../../events/view'

export default {
  name: 'viewLink',
  inject: ['dispatch'],
  props: {
    view: String
  },
  methods: {
    trigger () {
      this.dispatch(changed({ view: this.view }))
    }
  }
}
</script>

// examples/todo-svelte/src/components/units/ViewLink.svelte
<script>
  import { createDispatch } from '@coriolis/coriolis-svelte'

  import { changed } from '../../events/view'

  const dispatchChanged = createDispatch(changed)

  export let view

  const trigger = () => dispatchChanged({ view })
</script>

<a href={view} on:click|preventDefault={trigger}><slot /></a>
