// examples/todo-svelte/src/components/units/TodoControl.svelte
<script>
import { getContext, createEventDispatcher, onMount, onDestroy } from 'svelte'

import { added, filter, filters } from '../../events/todo'
import { todolistFilterName } from '../../aggrs/todo'

const dispatch = getContext('dispatch')
const getSource = getContext('getSource')

let filterName
let textInput
let textInputValue

const subscription = getSource(todolistFilterName, newFilterName => { filterName = newFilterName })

const addItem = () => {
  if (!textInputValue) {
    return
  }

  dispatch(added({ text: textInputValue }))
  textInputValue = ''
  textInput.focus()
}

const setFilter = filterName => {
  dispatch(filter({ filterName }))
}

onMount(() => textInput.focus())
onDestroy(() => subscription.unsubscribe())

</script>

<div>
  <form on:submit|preventDefault={addItem}>
    <input
      type="text"
      placeholder="What should I do ?"
      bind:this={textInput}
      bind:value={textInputValue}
    />
    <button type="submit" disabled={!textInputValue}>Add</button>
  </form>
  <div>
    Show :
    {#each filters as filter (filter)}
    <button
      on:click|preventDefault={() => setFilter(filter)}
      disabled={filter === filterName}
    >
      {filter}
    </button>
    {/each}
  </div>
</div>

// examples/todo-vuejs/src/components/units/TodoControl.vue
<template>
  <div>
    <form ref="addForm" @submit.prevent="addItem">
      <input ref="textInput" type="text" placeholder="What should I do ?" v-model="textInputValue" />
      <button type="submit" :disabled="!textInputValue">Add</button>
    </form>
    <div>
      Show :
      <button
        v-for="filter in filters"
        :key="filter"
        @click.prevent="setFilter(filter)"
        :disabled="filter === filterName"
      >
        {{filter}}
      </button>
    </div>
  </div>
</template>

<script>
import { connect } from '../../libs/vuejs/connect'

import { added, filter, filters } from '../../events/todo'
import { todolistFilterName } from '../../projections/todo'

const TodoControl = {
  name: 'TodoControl',
  data: () => ({
    filters: filters.slice(),
    filterName: undefined,
    textInputValue: '',
  }),
  methods: {
    addItem() {
      if (!this.textInputValue) {
        return
      }
      this.$emit('added', { text: this.textInputValue })
      this.textInputValue = ''
      this.$refs.textInput.focus()
    },
    setFilter(filterName) {
      this.$emit('filter', { filterName })
    },
  },
  mounted() {
    this.$refs.textInput.focus()
  },
}

export default connect({
  mapProjection: {
    filterName: todolistFilterName,
  },
  eventDispatch: {
    added,
    filter,
  },
})(TodoControl)

</script>
