// examples/todo-svelte/src/components/units/ViewLink.svelte
<script>
  import { createDispatch } from '@coriolis/coriolis-svelte'

  import { changed } from '../../todo-core/events/view'

  const dispatchChanged = createDispatch(changed)

  export let view

  const trigger = () => dispatchChanged({ view })
</script>

<a href={view} on:click|preventDefault={trigger}><slot /></a>

// examples/todo-vuejs/src/components/units/ViewLink.vue
<template>
  <a :href="view" @click.prevent="trigger"><slot /></a>
</template>

<script>
import { connect } from '../../libs/vuejs/connect'

import { changed } from '../../todo-core/events/view'

const ViewLink = {
  name: 'ViewLink',
  props: {
    view: String,
  },
  methods: {
    trigger() {
      this.$emit('switch', { view: this.view })
    },
  },
}

export default connect({
  eventDispatch: {
    switch: changed,
  },
})(ViewLink)

</script>
