// examples/todo-svelte/src/components/units/TodoList.svelte
<script>
import { getContext, onDestroy } from 'svelte'

import TodoItem from './TodoItem.svelte'

import { filteredTodolist } from '../../aggrs/todo'

const getSource = getContext('getSource')

let todolist = []

const subscription = getSource(filteredTodolist)
    .subscribe(newtodolist => { todolist = newtodolist })

onDestroy(() => subscription.unsubscribe())

</script>

<ol>
{#each todolist as item (item.id)}
  <TodoItem
    id={item.id}
    text={item.text}
    isDone={item.done}
  />
{/each}
</ol>

// examples/todos/src/components/units/TodoList.vue
<template>
  <ol>
    <TodoItem
      v-for="item in todolist"
      :key="item.id"
      :id="item.id"
      :text="item.text"
      :done="item.done"
    />
  </ol>
</template>

<script>
import TodoItem from './TodoItem'

import { filteredTodolist } from '../../aggrs/todo'

export default {
  name: 'TodoList',
  components: {
    TodoItem
  },
  inject: [
    'pipeAggr'
  ],
  data: () => ({
    todolist: []
  })
  created () {
    this.todolistSubscription = this.pipeAggr(filteredTodolist).subscribe(todolist => {
      // kind of clone objects to avoid mutate aggr's state
      // TODO: find a better way to prevent vue from mutate the nested data
      this.todolist = todolist.map(item => ({ ...item }))
    })
  },
  beforeDestroy () {
    this.todolistSubscription.unsubscribe()
  }
}
</script>
