// examples/todo-svelte/src/components/units/TodoItem.svelte
<script>
  import { getContext } from 'svelte'

  import { edited, removed, done, reset } from '../../events/todo'

  const dispatch = getContext('dispatch')

  export let id
  export let text
  export let isDone

  let doneCheckbox

  const removeItem = () => dispatch(removed({ id }))

  const editItem = () => dispatch(edited({ id, text }))

  const checkItem = () => {
    const eventBuilder = doneCheckbox.checked ? done : reset
    dispatch(eventBuilder({ id }))
  }
</script>

<style>
  input[type=text] {
    border: none;

  }
  .done  input[type=text] {
    text-decoration: line-through;
  }
</style>

<li class:done={isDone}>
  <input type="text" value={text} on:change|preventDefault={editItem} />
  <input bind:this={doneCheckbox} type="checkbox" checked={isDone} on:change|preventDefault={checkItem} />
  <button on:click|preventDefault={removeItem}>Remove</button>
</li>

// examples/todos/src/components/units/TodoItem.vue
<template>
  <li :class="{ done }">
    <input ref="textInput" type="text" :value="text" @change.prevent="editItem" />
    <input ref="doneCheckbox" type="checkbox" :checked="done" @change.prevent="checkItem" />
    <button @click.prevent="removeItem">Remove</button>
  </li>
</template>

<script>
import { edited, removed, done, reset } from '../../events/todo'

export default {
  name: 'todo-item',
  inject: [
    'dispatch'
  ],
  props: {
    id: Number,
    text: String,
    done: Boolean
  },
  methods: {
    removeItem () {
      this.dispatch(removed({ id: this.id }))
    },
    editItem () {
      this.dispatch(edited({ id: this.id, text: this.$refs.textInput.value() }))
    },
    checkItem () {
      const buildEvent = this.$refs.doneCheckbox.checked ? done : reset
      this.dispatch(buildEvent({ id: this.id }))
    }
  }
}
</script>

<style lang="scss" scoped>
input[type=text] {
  border: none;

  .done & {
    text-decoration: line-through;
  }
}
</style>
